blank_issues_enabled: false
contact_links:
    - name: Questions and usage help
      url: https://github.com/PBK-B/i18next-plugin-eslint/discussions
      about: Ask and discuss usage questions in Discussions.
